version: "{branch}-{build}"
cache:
  - '%LOCALAPPDATA%\pip\Cache'
environment:
  PYPI_PASSWD:
    secure: pp1j5lAB9NN8ZDasgY+oxoGrNw0+4gGzbNZmHVwJkCzUyrNBP5ZIuCrwjmx4q6ifg7RMiE3bVt9MljFCJh3XpsvVOAcx+AGKsHSjtXd40HM=

init:
  - ps: "ls C:/Python*"

install:
  - SET PATH=%PYTHON%;%PYTHON%\scripts;%PATH%
  - echo "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 > "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64\vcvars64.bat"
  - pip install -r dev-requirements.txt

build_script:
  - python -m pip install -U pip setuptools
  - pip install cibuildwheel==1.0.0
  - cibuildwheel --output-dir wheelhouse

test_script:
  - pip install codecov
  - python setup.py test
  - codecov --required

deploy_script:
  - ps: >-
      if($env:appveyor_repo_tag -eq 'True') {
          $env:Path += ";C:\Python37;C:\Python37\scripts"
          pip install twine
          twine upload --username whtsky --password $env:PYPI_PASSWD wheelhouse/bencoder*.whl
      }

artifacts:
  - path: wheelhouse/bencoder*.whl
