test: &test
  working_directory: ~/bencoder.pyx
  steps:
    - checkout
    - run:
        name: install dependencies
        command: |
          sudo pip install -r tox-requirements.txt
    - restore_cache:
        keys:
          - tox-env-{{ checksum "test-requirements" }}-{{ checksum "build-requirements.txt" }}
          - tox-env-
    - run:
        name: test
        command: |
          tox -e ${CIRCLE_JOB}
    - save_cache:
        key: tox-env-{{ checksum "test-requirements" }}-{{ checksum "build-requirements.txt" }}
        paths:
          - .tox
test_pypy: &test_pypy
  working_directory: ~/bencoder.pyx
  steps:
    - checkout
    - run:
        name: install dependencies
        command: |
          pip install -r tox-requirements.txt
    - run:
        name: test
        command: |
          tox -e ${CIRCLE_JOB}

version: 2
jobs:
  #
  # test
  #
  py27:
    docker:
      - image: circleci/python:2.7
    <<: *test
  py35:
    docker:
      - image: circleci/python:3.5
    <<: *test
  py36:
    docker:
      - image: circleci/python:3.6
    <<: *test
  py37:
    docker:
      - image: circleci/python:3.7
    <<: *test
  py38:
    docker:
      - image: circleci/python:3.8
    <<: *test
  pypy:
    docker:
      - image: pypy:2
    <<: *test_pypy
  pypy3:
    docker:
      - image: pypy:3
    <<: *test_pypy

workflows:
  version: 2
  test_and_build:
    jobs:
      - py27
      - py35
      - py36
      - py37
      - py38
      - pypy
      - pypy3
