test: &test
  working_directory: ~/bencoder.pyx
  steps:
    - checkout
    - run:
        name: install dependencies
        command: |
          pip install -r dev-requirements.txt
    - run:
        name: test
        command: |
          python setup.py test
    - run:
        name: upload coverage
        command: |
          pip install codecov
          codecov --required
version: 2
jobs:
  #
  # test
  #
  py27:
    docker:
      - image: circleci/python:2.7
    <<: *test
  py35:
    docker:
      - image: circleci/python:3.5
    <<: *test
  py36:
    docker:
      - image: circleci/python:3.6
    <<: *test
  py37:
    docker:
      - image: circleci/python:3.7
    <<: *test
  py38:
    docker:
      - image: circleci/python:3.8
    <<: *test
  pypy:
    docker:
      - image: pypy:2
    <<: *test
  pypy3:
    docker:
      - image: pypy:3
    <<: *test

workflows:
  version: 2
  test_and_build:
    jobs:
      - py27
      - py35
      - py36
      - py37
      - py38
      - pypy
      - pypy3
