on:
  push:
  pull_request:
name: test
jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          architecture: "x64"
      - run: python -m pip install -U pip wheel setuptools
      - run: pip install cython
      - run: pip install .
      - run: python setup.py test
      - uses: codecov/codecov-action@v2.1.0
